### ISSUE TITLE
nothing

### ISSUE THREAD

**Issue by rmwphd** [40-percent/server-meta#15]

**Comment by FrancisUsher** [comment]
This is inaccurate. Pinging @everyone is restricted to mods-only already. Individuals can only be granted permission to ping everyone on a one-off basis.

**Comment by rmwphd** [comment]
Okay then how did some rando from some desk mat gb ping everybody today and then not even know they'd done it?

**Comment by rmwphd** [comment]
See: https://discord.com/channels/527180441950617611/995898214622437458/1026554185975607408

That person is not listed as a mod, they're a Creator.

@FrancisUsher please advise

**Comment by FrancisUsher** [comment]
Sounds like something to ask the mods about
