### ISSUE TITLE
Newcomer Channel

### ISSUE THREAD

**Issue by matthewdias** [40-percent/server-meta#3]
### Problem

- 40s has a bad reputation for being unwelcoming and/or toxic
- Newcomers asking for help have to navigate the large list of channels and very active discussion to try to get their questions answered
- Help can get in the way of discussion and vice versa, leading to unproductive tangents

### Goals

- Create a space for people new to 40s and custom keyboards to ask basic questions and receive direct answers
- Foster a welcoming atmosphere for those that are interested in joining the community
- Make it easier to provide help without it being mixed in with arguments, opinions, and/or general discussion
- Reduce the opportunity for newcomers to get defensive by making them feel like we want to help, and by treating what might seem like lazy/bad faith asking as just being uninformed

### Action Items
- Make a new channel dedicated to welcoming newcomers and letting them ask basic questions (`#newcomer-help` or something)
- Make the purpose of the channel clear via an announcement, and pinned info or channel topic, to discourage opining/arguing and encourage informing/helping resolve problems.
- Direct new users to the channel via the welcome screen
- Create policy to remind people of the channel purpose if it gets off track
- Pin some helpful info/FAQs
- There was discussion of a helper role, but it seems like if the above items are executed people should get the hint and stay out if they aren't going to be helpful

### Counter-argument
- We should change the general server behavior instead of trying to quarantine it

Rebuttal: It's unrealistic to try to change the established culture of lots of participating members without heavy enforcement. Arguably more productive to add structure that encourages different behavior in different places (this has already worked at least okay in off-topic vs keyboard-chat, though there is room for improvement)

**Comment by FrancisUsher** [comment]
A couple other pitfalls to keep in mind.

One is that it's a new channel, and people already complain about how many channels there are.

Another is that people seem to naturally resist channels with stricter moderation policies.

**Comment by FrancisUsher** [comment]
I'm not convinced that this would be anything except another off-topic channel. Leaning towards a no on this one as it would just create another disaster channel to moderate.

**Comment by tominabox1** [comment]
what about rename the current help channel to newbie help?

**Comment by dingusxmcgee** [comment]
I'll catvibe to a newbiew help channel. Might as well try it.

**Comment by matthewdias** [comment]
If we also did this item
> Direct new users to the channel via the welcome screen

I think we can close this issue.

**Comment by ridingqwerty** [comment]
@tominabox1 went ahead and already created the channel, but I still want my piece reiterated here:

While I'm not opposed to a newbie channel at all, I don't believe we have a newbie toxicity problem.  A reputation, perhaps, but this has been the case forever and probably has more to do with certain members calling out keyset designers on geekhack, or perhaps seeing "bants" taking place among otherwise friendly members and extrapolating that we are jerks from there.

As far as "newbie-help" I don't think it's much different from the currently existing "help" channel.  But I can see value in a place for newcomers to ask "simple" questions not suited for the usual hardware or firmware troubleshooting that takes place in the old "help" channel.

Just my $0.02. :v:

**Comment by ridingqwerty** [comment]
It may be useful to have an opt-in and/or mod-vetted `@helpers` role, with some kind of small power over #newbie-help only to kick people from the channel or delete posts that aren't helpful.  If it turns into a meme-zone it'll completely defeat the purpose of the channel.

**Comment by matthewdias** [comment]
with welcome message added i think this can be considered resolved for now. seems like we're ok without helpers role currently
