### ISSUE TITLE
Too many moderators in 40% discord, a proposal to lower the amount so moderation can be more focused.

### ISSUE THREAD

**Issue by kokaloo** [40-percent/server-meta#4]
**Problems:**

1. -Too many moderators in the 40% Mechanical Keyboard Discord.
2. -Dysfunctional moderation techniques
3. -Unfocused moderation; moderators don't have a specific job or duty leaving those unfit to do certain jobs doing them

**Goals**
1. -To create less issues when moderators feel the need to flock to an issue all at once, rather letting moderators with specific qualities handle the job.
2. -Eliminate the Mini-mod role

**Action Items**
1. -All moderators must report to a game of Mario Party 2, where they will face off playing [Bowser's Big Blast](https://www.youtube.com/watch?v=GXTRNSuC_YQ) following the bracket [created here.](https://challonge.com/4z00h79h)
2. -Each moderator will have another moderator they will face with two bot players. The players will play a set of 2/3, determining who moves further into the bracket. Any game resulting in a bot winning is not counted and must be played again.
3. -The games and bracket stops once we reach two moderators in total, and those two moderators will be crowned the sole designated moderation team of the 40% Mechanical Keyboard Discord.

**Comment by dingusxmcgee** [comment]
you have my attention.

**Comment by ridingqwerty** [comment]
Why doesn't TJ, the largest mod, simply eat the other 7?

**Comment by MelindaBirkenstock** [comment]
This could certainly work, but is there any way to confirm that mods wouldn't cheat to win a position just so they can bully newbies? Y'know, since everyone is inherently toxic and nobody in 40s can be respectful of others.

**Comment by chaoskills08** [comment]
Whilst I agree with the challenge, might I offer a proposal to change the game to Rocket League and, thus, add me to the bracket?

**Comment by rainkeebs** [comment]
May I contribute to this discussion by suggesting a change in competition to something the whole server can join in, a battle royale of sorts to decide the mod team?

**Comment by FrancisUsher** [comment]
Please don't make meme posts on here. That's the whole point of this forum. I will ban people who post memes here from contributing to the repository.
