### ISSUE TITLE
Speed typing channel

### ISSUE THREAD

**Issue by ASH-ART** [40-percent/server-meta#7]
# Issue : every few days, conversation in #keyboard-chat gets flooded by typing tests and general speed typing chat

_Proposed solution : Creating a #typing-tests channel under the Interests category to talk about this specific subject._

### What would this channel be used for?

- General typing discussion
- Occasional community-hosted events (eg : typing competitions, typing with certain constraints etc...)
- A PB wall pinned to flex how fast your fingers moves to the mere 60wpm mortals

**Comment by KnoblesseOblige** [comment]
We have one of these channels now. Closing.
