### ISSUE TITLE
Make Server Meta Meta Group

### ISSUE THREAD

**Issue by cjcodell1** [40-percent/server-meta#8]
Now that there are 12 channels (or 11 after Secret Santa ends) in the `Server Meta 💡`, I suggest creating a new channel group called  `Server Meta 💡💡` and move some of the new meta `Server Meta 💡` into there. 

Or move some of the channels into existing channel groups. `typing-tests` could go into interests since there is a small subset of users who are very competitive and care about their speed. Both `typing-tests` and `soundtest` have no _meta_ conversations about the server, so the `Interests` group is a better place for them. `numbers-and-other-characters` very nicely fits into `Welcome` for all the new users with their first 40% in dire need of help typing numbers.

`Server Meta 💡` could also be reordered. `announcements`, `suggestion-box`, and `showcase` are some of the most important channels in this group. They should be at the top.

**Comment by cjcodell1** [comment]
Implementing these changes will help cut down on spam from users misclicking channels. This server had a _major_ disagreement in regards to the posting of typing tests. Some users like myself have the typing test channel muted. Accidently posted typing tests can cause extreme trauma when posted in an unmuted channel. In fact, if this typing test had not been sent in the wrong channel, at least 11 off topic messages could have been prevented. This is about **5 inches** of screen space in the Cozy message display (or, for our European friends, 3 inches in the Compact message display).

![image](https://user-images.githubusercontent.com/26935146/125695440-aff3bced-10f6-4592-9810-f79f91254bea.png)

**Comment by FrancisUsher** [comment]
Really great idea. Marking with a label of "good first issue" as a simple application of machine learning would solve this problem, which anyone should be able to trivially do.

**Comment by KnoblesseOblige** [comment]
I think that there are a lot of good suggestions in the original post here.

> Or move some of the channels into existing channel groups. `typing-tests` could go into interests since there is a small subset of users who are very competitive and care about their speed. Both `typing-tests` and `soundtest` have no _meta_ conversations about the server, so the `Interests` group is a better place for them. `numbers-and-other-characters` very nicely fits into `Welcome` for all the new users with their first 40% in dire need of help typing numbers.

I would agree that `typing-tests` deserves to live in interests rather than meta, since it's not a discussion about the server itself. That being said, `soundtest` is a read-only channel so it is very much a meta channel just like `showcase`.

I also think that tossing the newly created `numbers-and-other-characters` in the Welcome channel is a great improvement.

> `Server Meta 💡` could also be reordered. `announcements`, `suggestion-box`, and `showcase` are some of the most important channels in this group. They should be at the top.

I also think that this is a good improvement. I will look at the other meta channels as well and see if any of those can be ordered more intentionally.

**Comment by KnoblesseOblige** [comment]
All actionable items have been completed. Closing for now.
